// ═══════════════════════════════════════════════════════════════
// Xpecto Shield Dev — Dashboard API Routes (Catch-All)
// ═══════════════════════════════════════════════════════════════

import { NextRequest, NextResponse } from 'next/server'
import {
  addIncident,
  getIncidents,
  getStats,
  getBlockedIPsList,
  blockIP,
  unblockIP,
  getReportsList,
  getSettings,
  saveSettings,
} from '../store'

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  const { path } = await params
  const route = path.join('/')

  switch (route) {
    case 'stats':
      return NextResponse.json(getStats())

    case 'incidents': {
      const url = new URL(request.url)
      const page = parseInt(url.searchParams.get('page') || '1')
      const limit = parseInt(url.searchParams.get('limit') || '20')
      const category = url.searchParams.get('category') || undefined
      return NextResponse.json(getIncidents(page, limit, category))
    }

    case 'blocked-ips': {
      const url = new URL(request.url)
      const page = parseInt(url.searchParams.get('page') || '1')
      const limit = parseInt(url.searchParams.get('limit') || '20')
      return NextResponse.json(getBlockedIPsList(page, limit))
    }

    case 'reports':
      return NextResponse.json(getReportsList())

    case 'settings':
      return NextResponse.json(getSettings())

    default:
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  const { path } = await params
  const route = path.join('/')

  switch (route) {
    case 'log-incident': {
      const body = await request.json()
      const incident = addIncident(body)
      return NextResponse.json({ ok: true, id: incident.id })
    }

    case 'block-ip': {
      const body = await request.json()
      blockIP(body.ip, body.duration || 86400)
      return NextResponse.json({ ok: true })
    }

    case 'unblock-ip': {
      const body = await request.json()
      unblockIP(body.ip)
      return NextResponse.json({ ok: true })
    }

    case 'settings': {
      const body = await request.json()
      saveSettings(body)
      return NextResponse.json({ ok: true })
    }

    case 'setup':
      return NextResponse.json({ message: 'Dev mode — no database setup needed!' })

    case 'generate-report':
      return NextResponse.json({
        report: {
          id: 'demo-report',
          createdAt: new Date().toISOString(),
          dateRangeStart: new Date(Date.now() - 7 * 86400000).toISOString(),
          dateRangeEnd: new Date().toISOString(),
          incidentCount: 25,
          executiveSummary: 'This is a demo report in dev mode. In production, this would be generated by AI analytics using the configured LLM provider.',
          patternAnalysis: JSON.stringify({ topPattern: "SQL Injection via ' OR '1'='1'", frequency: 'High' }),
          trendAnalysis: JSON.stringify({ trend: 'Increasing', peakHour: '14:00' }),
          riskAssessment: JSON.stringify({ overallRisk: 'Medium', criticalAssets: ['/api/auth', '/api/admin'] }),
          recommendations: JSON.stringify(['Enable rate limiting', 'Update WAF rules', 'Review authentication endpoints']),
          threatLevel: 'medium',
          modelUsed: 'dev-mode (mock)',
        },
      })

    default:
      return NextResponse.json({ error: 'Not found' }, { status: 404 })
  }
}
